services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8082:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: